version: '3.8'
services:
  dev-db:
    container_name: dev-db
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: portfolio
    volumes:
      - postgres_data:/var/lib/postgresql/data
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: portfolio
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
      - 5555:5555
    depends_on:
      - dev-db
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - /app/node_modules
      - ./prisma:/app/prisma
      - ./uploads:/app/uploads
volumes:
  postgres_data:
